server:
  port: 8080

spring:
  datasource:
    username: zzbzcglxt
    password: qwertyuiop
    url: jdbc:mysql://localhost:3306/zzbzcglxt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
      exclude: data/**


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.demstudio.zzbzcglxt.domain

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql